### ISSUE TITLE
New NPM build failure on Circle

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#85] opened 2017-12-22 23:32 UTC
- Failing build for commit e154892: https://circleci.com/gh/PlanScore/PlanScore/391
- Previously successful build for commit ea4232d: https://circleci.com/gh/PlanScore/PlanScore/387

Error:

    ERROR in ./planscore_common.js
    Module not found: Error: Can't resolve 'tinygradient' in '/home/ubuntu/PlanScore'
     @ ./planscore_common.js 16:46-69
     @ ./home/index.js6

**Comment by danrademacher** [comment] 2017-12-22 23:45
Hmm, that's a new dependency that @gregallensworth added. Locally, I needed to do `yarn install` again. First new dependency since previous successful build.

So from that I would say we need to add:
` - yarn install` 
before 
`- npm run build` 
in the `yml` file

**Comment by danrademacher** [comment] 2017-12-22 23:59
I wonder if we need to take any action to make `yarn` available. I discovered this not so helpful StackOverflow version of the same question -- https://stackoverflow.com/questions/43376979/use-yarn-with-circleci-2-0.

**Comment by danrademacher** [comment] 2017-12-23 00:26
Adding `-yarn install` didn't work. Trying to suss this out this while Greg focuses on other issues.

Here's teh error we're getting:
``
yarn install v1.1.0
warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
[1/4] Resolving packages...
⠁ [2/4] Fetching packages...
error webpack-dev-server@2.9.7: The engine "node" is incompatible with this module. Expected version ">=4.7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn install returned exit code 1

Action failed: yarn install
```

**Comment by migurski** [comment] 2017-12-23 00:52
Looks like Circle can be told to use a newer version of node. Can you try adding [this machine clause](https://circleci.com/docs/1.0/configuration/#machine) with [Circle’s newest supported Node version](https://circleci.com/docs/1.0/build-image-trusty/#nodejs)?

```
machine:
  node:
    version: 8.2.0
```

**Comment by danrademacher** [comment] 2017-12-23 01:43
And now passing, yay!

**Closed by danrademacher** 2017-12-23 01:43 UTC
Labels: bug, gh-pages website
